variables:
  LATEST: "1.1"

stages:
  - build

.build_job:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  after_script:
    - docker image prune -a -f
  tags:
    - hz-afs

build_dev:
  extends: .build_job
  script:
    - echo 'build dev'
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
  only:
    - master

build_latest:
  extends: .build_job
  script:
    - echo 'build latest'
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $LATEST
  except:
    - tags

build_tag:
  extends: .build_job
  script:
    - echo 'build' $CI_COMMIT_TAG
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  except:
    - branches

