library:
  source-dirs: src
tests:
  send-email-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - send-email
copyright: 2020 Aleksey Danilevsky
maintainer: alexey.danilevsky@gmail.com
dependencies:
  - hspec
  - aeson
  - base >= 4.7 && < 5
  - HaskellNet
  - HaskellNet-SSL
  - hslogger
  - http-types
  - listsafe
  - mime-mail
  - mtl
  - network
  - regex-compat
  - split
  - text
  - utf8-string
  - wai
  - wai-extra
  - warp
  - yaml
name: send-email
version: 1.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Aleksey Danilevsky
github: githubuser/send-email
license: BSD3
executables:
  send-email:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - send-email
description: Please see the README on GitHub at <https://github.com/githubuser/send-email#readme>
